-- 파일명: R20260423_01_drop_chat_tables.sql
-- 목적: 채팅 기능 롤백용 객체 삭제
-- 작성일: 2026-04-23

DROP TABLE TBL_CHAT_READ CASCADE CONSTRAINTS;
DROP TABLE TBL_CHAT_MESSAGE CASCADE CONSTRAINTS;
DROP TABLE TBL_CHAT_ROOM CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CHAT_MESSAGE_ID;
DROP SEQUENCE SEQ_CHAT_ROOM_ID;