CREATE UNIQUE INDEX UK_CHAT_ROOM_APPLICATION
ON TBL_CHAT_ROOM (CASE WHEN ROOM_TYPE = 'APPLICATION' THEN FK_APPLICATION_ID END);
/

CREATE UNIQUE INDEX UK_CHAT_ROOM_OFFER
ON TBL_CHAT_ROOM (CASE WHEN ROOM_TYPE = 'OFFER' THEN FK_OFFER_SUBMIT_ID END);
/

CREATE INDEX IDX_CHAT_ROOM_COMPANY
ON TBL_CHAT_ROOM (FK_COMPANY_MEMBERID, ROOM_STATUS, LAST_MESSAGE_AT DESC);
/

CREATE INDEX IDX_CHAT_ROOM_JOBSEEKER
ON TBL_CHAT_ROOM (FK_JOBSEEKER_MEMBERID, ROOM_STATUS, LAST_MESSAGE_AT DESC);
/

CREATE INDEX IDX_CHAT_MESSAGE_ROOM_ID
ON TBL_CHAT_MESSAGE (FK_ROOM_ID, MESSAGE_ID DESC);
/

CREATE INDEX IDX_CHAT_READ_MEMBER
ON TBL_CHAT_READ (FK_MEMBERID, FK_ROOM_ID);
/

COMMIT;