CREATE SEQUENCE SEQ_CHAT_ROOM_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE SEQUENCE SEQ_CHAT_MESSAGE_ID
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
/

CREATE TABLE TBL_CHAT_ROOM (
    ROOM_ID                 NUMBER          NOT NULL,
    ROOM_TYPE               VARCHAR2(20)    NOT NULL,
    FK_APPLICATION_ID       NUMBER          NULL,
    FK_OFFER_SUBMIT_ID      NUMBER          NULL,
    FK_JOB_ID               NUMBER          NOT NULL,
    FK_COMPANY_MEMBERID     VARCHAR2(50)    NOT NULL,
    FK_JOBSEEKER_MEMBERID   VARCHAR2(50)    NOT NULL,
    CREATED_BY              VARCHAR2(50)    NOT NULL,
    ROOM_STATUS             NUMBER(1)       DEFAULT 1 NOT NULL,
    LAST_MESSAGE_PREVIEW    VARCHAR2(300),
    LAST_MESSAGE_AT         DATE,
    CREATED_AT              DATE            DEFAULT SYSDATE NOT NULL,
    CLOSED_AT               DATE,
    CONSTRAINT PK_CHAT_ROOM PRIMARY KEY (ROOM_ID),
    CONSTRAINT FK_CHAT_ROOM_APPLICATION FOREIGN KEY (FK_APPLICATION_ID) REFERENCES TBL_JOB_APPLICATION (APPLICATION_ID),
    CONSTRAINT FK_CHAT_ROOM_OFFER_SUBMIT FOREIGN KEY (FK_OFFER_SUBMIT_ID) REFERENCES TBL_OFFER_SUBMIT (OFFER_SUBMIT_ID),
    CONSTRAINT FK_CHAT_ROOM_JOB FOREIGN KEY (FK_JOB_ID) REFERENCES TBL_JOB_POSTING (JOB_ID),
    CONSTRAINT FK_CHAT_ROOM_COMPANY_MEMBER FOREIGN KEY (FK_COMPANY_MEMBERID) REFERENCES TBL_MEMBER (MEMBERID),
    CONSTRAINT FK_CHAT_ROOM_JOBSEEKER_MEMBER FOREIGN KEY (FK_JOBSEEKER_MEMBERID) REFERENCES TBL_MEMBER (MEMBERID),
    CONSTRAINT FK_CHAT_ROOM_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES TBL_MEMBER (MEMBERID),
    CONSTRAINT CK_CHAT_ROOM_TYPE CHECK (ROOM_TYPE IN ('APPLICATION', 'OFFER')),
    CONSTRAINT CK_CHAT_ROOM_STATUS CHECK (ROOM_STATUS IN (0, 1)),
    CONSTRAINT CK_CHAT_ROOM_REF CHECK ((ROOM_TYPE = 'APPLICATION' AND FK_APPLICATION_ID IS NOT NULL AND FK_OFFER_SUBMIT_ID IS NULL) OR (ROOM_TYPE = 'OFFER' AND FK_APPLICATION_ID IS NULL AND FK_OFFER_SUBMIT_ID IS NOT NULL))
);
/

CREATE TABLE TBL_CHAT_MESSAGE (
    MESSAGE_ID          NUMBER            NOT NULL,
    FK_ROOM_ID          NUMBER            NOT NULL,
    SENDER_MEMBERID     VARCHAR2(50)      NOT NULL,
    MESSAGE_TYPE        VARCHAR2(20)      DEFAULT 'TEXT' NOT NULL,
    CONTENT             VARCHAR2(1000)    NOT NULL,
    DELETED_YN          NUMBER(1)         DEFAULT 0 NOT NULL,
    CREATED_AT          DATE              DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CHAT_MESSAGE PRIMARY KEY (MESSAGE_ID),
    CONSTRAINT FK_CHAT_MESSAGE_ROOM FOREIGN KEY (FK_ROOM_ID) REFERENCES TBL_CHAT_ROOM (ROOM_ID),
    CONSTRAINT FK_CHAT_MESSAGE_SENDER FOREIGN KEY (SENDER_MEMBERID) REFERENCES TBL_MEMBER (MEMBERID),
    CONSTRAINT CK_CHAT_MESSAGE_TYPE CHECK (MESSAGE_TYPE IN ('TEXT')),
    CONSTRAINT CK_CHAT_MESSAGE_DELETED CHECK (DELETED_YN IN (0, 1))
);
/

CREATE TABLE TBL_CHAT_READ (
    FK_ROOM_ID             NUMBER         NOT NULL,
    FK_MEMBERID            VARCHAR2(50)   NOT NULL,
    LAST_READ_MESSAGE_ID   NUMBER,
    LAST_READ_AT           DATE,
    UPDATED_AT             DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_CHAT_READ PRIMARY KEY (FK_ROOM_ID, FK_MEMBERID),
    CONSTRAINT FK_CHAT_READ_ROOM FOREIGN KEY (FK_ROOM_ID) REFERENCES TBL_CHAT_ROOM (ROOM_ID),
    CONSTRAINT FK_CHAT_READ_MEMBER FOREIGN KEY (FK_MEMBERID) REFERENCES TBL_MEMBER (MEMBERID),
    CONSTRAINT FK_CHAT_READ_MESSAGE FOREIGN KEY (LAST_READ_MESSAGE_ID) REFERENCES TBL_CHAT_MESSAGE (MESSAGE_ID)
);
/

COMMIT;